services:
  app:
    image: oven/bun:latest
    working_dir: /app
    command: 'bun run dev'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    expose: [3000]
    environment:
      - HANDY_URL=http://localhost:8080
    networks:
      - vite
networks:
  vite:
    driver: bridge
